openapi: 3.0.3
info:
  title: Global Indexer
  version: 0.1.0
servers:
  - url: https://gi.rss3.io
    description: Production
  - url: https://gi.rss3.dev
    description: Development
  - url: http://localhost
    description: Localhost
tags:
  - name: Default
  - name: Bridge
  - name: Stake
  - name: Chips
  - name: Snapshots
  - name: Node
paths:
  /bridge/transactions:
    get:
      description: "Get bridge transactions"
      tags:
        - Bridge
      parameters:
        - name: cursor
          in: query
          schema:
            type: string
        - name: sender
          in: query
          schema:
            type: string
        - name: receiver
          in: query
          schema:
            type: string
        - name: address
          in: query
          schema:
            type: string
        - name: type
          in: query
          schema:
            type: string
            enum:
              - deposit
              - withdraw
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/BridgeTransaction"
              example:
                data:
                  - id: "0xdbfa26e70977dfe2d68f3da7dd7d9e0c04136ecf14e80b98b209314ae7c462ff"
                    sender: "0x3b6d02a24df681ffdf621d35d70aba7adaac07c1"
                    receiver: "0x3b6d02a24df681ffdf621d35d70aba7adaac07c1"
                    token:
                      address:
                        l1: "0x3ef1d5be1e2ce46c583a0c8e511f015706a0ab23"
                        l2: "0x4200000000000000000000000000000000000042"
                      value: "10000000000000000000000"
                    event:
                      deposit:
                        initialized:
                          block:
                            hash: "0x7735d45a54e91e836881c2f185766b391f335b53734b0a57f6c8843f66d03a13"
                            number: 5223592
                            timestamp: 1707118764
                          transaction:
                            hash: "0x28e8d8f6cbbdfcf14501ebf0bbd11647dfabab371fc7a989a1e441321af6a6ee"
                            index: 49
                        finalized:
                          block:
                            hash: "0xb0208c1b76aca5d51cb3cde5d10a90f20c2e520c935fbb99af0b66031489433e"
                            number: 117285
                            timestamp: 1707118890
                          transaction:
                            hash: "0x493972cb6219c74071c69fd9279df74b8cebbac4d087259991253e58930a4edb"
                            index: 1
                cursor: "0xdbfa26e70977dfe2d68f3da7dd7d9e0c04136ecf14e80b98b209314ae7c462ff"
  /bridge/transactions/{id}:
    get:
      description: "Get bridge transaction by id"
      tags:
        - Bridge
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/BridgeTransaction"
              example:
                data:
                  id: "0xdbfa26e70977dfe2d68f3da7dd7d9e0c04136ecf14e80b98b209314ae7c462ff"
                  sender: "0x3b6d02a24df681ffdf621d35d70aba7adaac07c1"
                  receiver: "0x3b6d02a24df681ffdf621d35d70aba7adaac07c1"
                  token:
                    address:
                      l1: "0x3ef1d5be1e2ce46c583a0c8e511f015706a0ab23"
                      l2: "0x4200000000000000000000000000000000000042"
                    value: "10000000000000000000000"
                  event:
                    deposit:
                      initialized:
                        block:
                          hash: "0x7735d45a54e91e836881c2f185766b391f335b53734b0a57f6c8843f66d03a13"
                          number: 5223592
                          timestamp: 1707118764
                        transaction:
                          hash: "0x28e8d8f6cbbdfcf14501ebf0bbd11647dfabab371fc7a989a1e441321af6a6ee"
                          index: 49
                      finalized:
                        block:
                          hash: "0xb0208c1b76aca5d51cb3cde5d10a90f20c2e520c935fbb99af0b66031489433e"
                          number: 117285
                          timestamp: 1707118890
                        transaction:
                          hash: "0x493972cb6219c74071c69fd9279df74b8cebbac4d087259991253e58930a4edb"
                          index: 1
  /stake/transactions:
    get:
      description: "Get stake transactions"
      tags:
        - Stake
      parameters:
        - name: cursor
          in: query
          schema:
            type: string
        - name: staker
          in: query
          schema:
            type: string
        - name: node
          in: query
          schema:
            type: string
        - name: type
          in: query
          schema:
            type: string
            enum:
              - deposit
              - withdraw
              - stake
              - unstake
        - name: pending
          in: query
          schema:
            type: boolean
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/StakeTransaction"
              example:
                data:
                  - id: "0xbfbb8cbffc01c13c1f849ecfb53099309e189b362fd621addbfa9f5d03dcd0c1"
                    staker: "0xc8b960d09c0078c18dcbe7eb9ab9d816bcca8944"
                    node: "0x6727a51caefcaf1bc189a8316ea09f844644b195"
                    value: "8239445455124262851652"
                    chips:
                      - id: 2105
                        node: "0x6727a51caefcaf1bc189a8316ea09f844644b195"
                        owner: "0xc8b960d09c0078c18dcbe7eb9ab9d816bcca8944"
                        metadata:
                          name: "Chip #2105"
                          description: "Chip is a unique NFT that represents a node in the network. It is generated based on the node's address and token ID."
                          image: "https://gi.rss3.dev/chips/2105/image.svg"
                    event:
                      deposit:
                        deposited:
                          block:
                            hash: "0x37af6202ef8303485aa3db32be6668070b6b9c7e46521325f959369847482015"
                            number: 128115
                            timestamp: 1707140550
                          transaction:
                            hash: "0x823d988f7a18215ea850010131e5fa138d8d882ae4f95716d5791a45fac57833"
                            index: 1
                cursor: "0xbfbb8cbffc01c13c1f849ecfb53099309e189b362fd621addbfa9f5d03dcd0c1"
  /stake/transactions/{id}:
    get:
      description: "Get stake transaction by id"
      tags:
        - Stake
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/StakeTransaction"
  /stake/stakings:
    get:
      description: "Get a list of stakers and nodes"
      tags:
        - Stake
      parameters:
        - name: staker
          in: query
          schema:
            type: string
        - name: node
          in: query
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
        - name: cursor
          in: query
          schema:
            type: string
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/StakeStaking"
                  cursor:
                    type: string
                    example: "0x08d66b34054a174841e2361bd4746ff9f4905cc2"
              example:
                data:
                  - staker: "0x827431510a5d249ce4fdb7f00c83a3353f471848"
                    node: "0x3b6d02a24df681ffdf621d35d70aba7adaac07c1"
                    chips:
                      total: 1
                      showcase:
                        - id: 21
                          node: "0x3b6d02a24df681ffdf621d35d70aba7adaac07c1"
                          owner: "0x827431510a5d249ce4fdb7f00c83a3353f471848"
                          metadata:
                            name: "Chip #21"
                            description: "Chip is a unique NFT that represents a node in the network. It is generated based on the node's address and token ID."
                            image: "https://gi.rss3.dev/chips/21/image.svg"
                cursor: "MHg4Mjc0MzE1MTBhNWQyNDljZTRmZGI3ZjAwYzgzYTMzNTNmNDcxODQ4LTB4M2I2ZDAyYTI0ZGY2ODFmZmRmNjIxZDM1ZDcwYWJhN2FkYWFjMDdjMQ=="
  /stake/{owner}/profits:
    get:
      description: "Get the profit of the staker"
      tags:
        - Stake
      parameters:
        - name: owner
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      owner:
                        type: string
                      totalChipAmounts:
                        type: string
                      totalChipValues:
                        type: string
                      oneDay:
                        $ref: "#/components/schemas/ChipPNL"
                      oneWeek:
                        $ref: "#/components/schemas/ChipPNL"
                      oneMonth:
                        $ref: "#/components/schemas/ChipPNL"
  /chips:
    get:
      description: "Get all chips by chips id"
      tags:
        - Chips
      parameters:
        - name: cursor
          in: query
          schema:
            type: string
        - name: id
          in: query
          schema:
            type: array
            items:
              type: integer
        - name: node
          in: query
          schema:
            type: string
        - name: owner
          in: query
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/Chips"
                  cursor:
                    type: string
  /chips/{id}:
    get:
      description: "Get chips by chips id"
      tags:
        - Chips
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Chips"
        404:
          description: "Not found"
  /chips/{id}/image.svg:
    description: "Not found"
    get:
      description: "Get image by chips id"
      tags:
        - Chips
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: "OK"
          content:
            image/svg+xml:
              schema:
                type: string
        404:
          description: "Not found"
  /snapshots/nodes/count:
    get:
      description: "Get snapshots of the number of nodes"
      tags:
        - Snapshots
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        date:
                          type: string
                        count:
                          type: integer
              example:
                data:
                  - date: "2024-02-19"
                    count: 2
  /snapshots/nodes/minTokensToStake:
    post:
        description: "Get snapshots of the minimum number of tokens to stake"
        tags:
            - Snapshots
        requestBody:
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    nodeAddresses:
                      type: array
                      items:
                          type: string
                    onlyStartAndEnd:
                      type: boolean
                      description: "If true, only return the start and end minTokensToStake"
                  example:
                    nodeAddresses:
                      - "0x9c29e25d7e475caee73d4b7006f3b10e977773ac"
                      - "0x08d66b34054a174841e2361bd4746ff9f4905cc2"
                    onlyStartAndEnd: true
        responses:
            200:
              description: "OK"
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: "#/components/schemas/NodeMinTokensToStakeSnapshot"
  /snapshots/stakers/count:
    get:
      description: "Get snapshots of the number of stakers"
      tags:
        - Snapshots
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        date:
                          type: string
                        count:
                          type: integer
              example:
                data:
                  - date: "2024-02-19"
                    count: 2
  /snapshots/stakers/profits:
    get:
        description: "Get snapshots of the profit of stakers"
        tags:
            - Snapshots
        parameters:
          - name: ownerAddress
            in: query
            required: true
            schema:
              type: string
          - name: cursor
            in: query
            schema:
              type: string
          - name: limit
            in: query
            schema:
              type: integer
            description: "The number of snapshots to return, if not provided, return all snapshots"
          - name: beforeDate
            in: query
            schema:
              type: string
              format: date
            description: "The date before which the snapshots are returned"
          - name: afterDate
            in: query
            schema:
              type: string
              format: date
            description: "The date after which the snapshots are returned"
        responses:
          200:
            description: "OK"
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    data:
                      type: array
                      items:
                        $ref: "#/components/schemas/StakerProfitSnapshot"
                    cursor:
                      type: string
  /snapshots/operators/profits:
    get:
        description: "Get snapshots of the profit of operators"
        tags:
            - Snapshots
        parameters:
          - name: operator
            in: query
            required: true
            schema:
              type: string
          - name: cursor
            in: query
            schema:
              type: string
          - name: limit
            in: query
            schema:
              type: integer
            description: "The number of snapshots to return, if not provided, return all snapshots"
          - name: beforeDate
            in: query
            schema:
              type: string
              format: date
            description: "The date before which the snapshots are returned"
          - name: afterDate
            in: query
            schema:
              type: string
              format: date
            description: "The date after which the snapshots are returned"
        responses:
          200:
            description: "OK"
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    data:
                      type: array
                      items:
                        $ref: "#/components/schemas/OperatorProfitSnapshot"
                    cursor:
                      type: string

  /nodes:
    get:
      description: "Get all nodes"
      tags:
        - Node
      parameters:
        - name: cursor
          in: query
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: "The number of nodes to return, default is 10, maximum is 50"
          required: false
          schema:
            type: integer
            default: 10
            minimum: 1
            maximum: 50
        - name: nodeAddress
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
            default: []
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                 $ref: "#/components/schemas/Node"
        404:
          description: "Not found"
        500:
          description: "Internal Server Error"
  /nodes/{address}:
    get:
      description: "Get node by address"
      tags:
        - Node
      parameters:
        - name: address
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Node"
        404:
          description: "Not found"
        500:
          description: "Internal Server Error"
  /nodes/{address}/avatar.svg:
    get:
      description: "Get avatar by node address"
      tags:
        - Node
      parameters:
        - name: address
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: "OK"
          content:
            image/svg+xml:
              schema:
                type: string
        404:
          description: "Not found"
        500:
          description: "Internal Server Error"
  /nodes/{address}/events:
    get:
      description: "Get transaction events by node address"
      tags:
        - Node
      parameters:
        - name: address
          in: path
          required: true
          schema:
            type: string
        - name: cursor
          in: query
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/NodeEvent"
                  cursor:
                    type: string

        404:
          description: "Not found"
        500:
          description: "Internal Server Error"

components:
  schemas:
    BridgeTransaction:
      type: object
      properties:
        id:
          type: string
        sender:
          type: string
        receiver:
          type: string
        token:
          type: object
          properties:
            address:
              type: object
              properties:
                l1:
                  type: string
                l2:
                  type: string
            value:
              type: string
        event:
          properties:
            deposit:
              type: object
              nullable: true
              properties:
                initialized:
                  $ref: "#/components/schemas/TransactionEvent"
                finalized:
                  $ref: "#/components/schemas/TransactionEvent"
            withdraw:
              type: object
              nullable: true
              properties:
                initialized:
                  $ref: "#/components/schemas/TransactionEvent"
                proved:
                  $ref: "#/components/schemas/TransactionEvent"
                finalized:
                  $ref: "#/components/schemas/TransactionEvent"
      example:
        id: "0xdbfa26e70977dfe2d68f3da7dd7d9e0c04136ecf14e80b98b209314ae7c462ff"
        sender: "0x3b6d02a24df681ffdf621d35d70aba7adaac07c1"
        receiver: "0x3b6d02a24df681ffdf621d35d70aba7adaac07c1"
        token:
          address:
            l1: "0x3ef1d5be1e2ce46c583a0c8e511f015706a0ab23"
            l2: "0x4200000000000000000000000000000000000042"
          value: "10000000000000000000000"
        event:
          deposit:
            initialized:
              block:
                hash: "0x7735d45a54e91e836881c2f185766b391f335b53734b0a57f6c8843f66d03a13"
                number: 5223592
                timestamp: 1707118764
              transaction:
                hash: "0x28e8d8f6cbbdfcf14501ebf0bbd11647dfabab371fc7a989a1e441321af6a6ee"
                index: 49
            finalized:
              block:
                hash: "0xb0208c1b76aca5d51cb3cde5d10a90f20c2e520c935fbb99af0b66031489433e"
                number: 117285
                timestamp: 1707118890
              transaction:
                hash: "0x493972cb6219c74071c69fd9279df74b8cebbac4d087259991253e58930a4edb"
                index: 1
    StakeTransaction:
      type: object
      properties:
        id:
          type: string
        staker:
          type: string
        node:
          type: string
        value:
          type: string
        chips:
          type: array
          nullable: true
          items:
            $ref: "#/components/schemas/Chips"
        event:
          properties:
            deposit:
              type: object
              nullable: true
              properties:
                requested:
                  $ref: "#/components/schemas/TransactionEvent"
                claimed:
                  $ref: "#/components/schemas/TransactionEvent"
            withdraw:
              type: object
              nullable: true
              properties:
                deposited:
                  $ref: "#/components/schemas/TransactionEvent"
            stake:
              type: object
              nullable: true
              properties:
                staked:
                  $ref: "#/components/schemas/TransactionEvent"
            unstake:
              type: object
              nullable: true
              properties:
                requested:
                  $ref: "#/components/schemas/TransactionEvent"
                claimed:
                  $ref: "#/components/schemas/TransactionEvent"
      example:
        id: "0xbfbb8cbffc01c13c1f849ecfb53099309e189b362fd621addbfa9f5d03dcd0c1"
        staker: "0xc8b960d09c0078c18dcbe7eb9ab9d816bcca8944"
        node: "0x6727a51caefcaf1bc189a8316ea09f844644b195"
        value: "8239445455124262851652"
        chips:
          - id: 2105
            node: "0x6727a51caefcaf1bc189a8316ea09f844644b195"
            owner: "0xc8b960d09c0078c18dcbe7eb9ab9d816bcca8944"
            metadata:
              name: "Chip #2105"
              description: "Chip is a unique NFT that represents a node in the network. It is generated based on the node's address and token ID."
              image: "https://gi.rss3.dev/chips/2105/image.svg"
        event:
          deposit:
            deposited:
              block:
                hash: "0x37af6202ef8303485aa3db32be6668070b6b9c7e46521325f959369847482015"
                number: 128115
                timestamp: 1707140550
              transaction:
                hash: "0x823d988f7a18215ea850010131e5fa138d8d882ae4f95716d5791a45fac57833"
                index: 1
    TransactionEvent:
      type: object
      nullable: true
      properties:
        block:
          properties:
            hash:
              type: string
            number:
              type: integer
            timestamp:
              type: integer
        transaction:
          type: object
          properties:
            hash:
              type: string
            index:
              type: integer
      example:
        block:
          hash: "0x200b26e118e51f23d052ef3aa92bc411dbd0a6ce811f511adb9f6049dc938614"
          number: 726419
          timestamp: 1708337158
        transaction:
          hash: "0x6595192f1193c2584c28e7d4b50b9208242bf9b4538933f0081d3f4625373d2f"
          index: 1
    StakeStaking:
      type: object
      properties:
        staker:
          type: string
        node:
          type: string
        chips:
          type: object
          properties:
            total:
              type: integer
            showcase:
              type: array
              items:
                $ref: "#/components/schemas/Chips"
      example:
        staker: 0x3b6d02a24df681ffdf621d35d70aba7adaac07c1
        node: "0x08d66b34054a174841e2361bd4746ff9f4905cc2"
        chips:
          total: 200
          showcase:
            - id: 275
              node: "0x08d66b34054a174841e2361bd4746ff9f4905cc2"
              owner: "0x3b6d02a24df681ffdf621d35d70aba7adaac07c1"
              metadata:
                name: "Chip #275"
                description: "Chip is a unique NFT that represents a node in the network. It is generated based on the node's address and token ID."
                image: "https://gi.rss3.dev/chips/275/image.svg"
            - id: 276
              node: "0x08d66b34054a174841e2361bd4746ff9f4905cc2"
              owner: "0x3b6d02a24df681ffdf621d35d70aba7adaac07c1"
              metadata:
                name: "Chip #276"
                description: "Chip is a unique NFT that represents a node in the network. It is generated based on the node's address and token ID."
                image: "https://gi.rss3.dev/chips/275/image.svg"
            - id: 277
              node: "0x08d66b34054a174841e2361bd4746ff9f4905cc2"
              owner: "0x3b6d02a24df681ffdf621d35d70aba7adaac07c1"
              metadata:
                name: "Chip #277"
                description: "Chip is a unique NFT that represents a node in the network. It is generated based on the node's address and token ID."
                image: "https://gi.rss3.dev/chips/275/image.svg"
            - id: 278
              node: "0x08d66b34054a174841e2361bd4746ff9f4905cc2"
              owner: "0x3b6d02a24df681ffdf621d35d70aba7adaac07c1"
              metadata:
                name: "Chip #278"
                description: "Chip is a unique NFT that represents a node in the network. It is generated based on the node's address and token ID."
                image: "https://gi.rss3.dev/chips/275/image.svg"
            - id: 279
              node: "0x08d66b34054a174841e2361bd4746ff9f4905cc2"
              owner: "0x3b6d02a24df681ffdf621d35d70aba7adaac07c1"
              metadata:
                name: "Chip #279"
                description: "Chip is a unique NFT that represents a node in the network. It is generated based on the node's address and token ID."
                image: "https://gi.rss3.dev/chips/275/image.svg"
    Chips:
      type: object
      properties:
        id:
          type: integer
        node:
          type: string
        owner:
          type: string
        metadata:
          type: object
          properties:
            name:
              type: string
            description:
              type: string
            image:
              type: string
        value:
          type: string
          description: "the value at time of minting"
        latestValue:
          type: string
          description: "The latest value of the chip"
      example:
        id: 474
        node: "0x08d66b34054a174841e2361bd4746ff9f4905cc2"
        owner: "0x3b6d02a24df681ffdf621d35d70aba7adaac07c1"
        metadata:
          name: "Chip #474"
          description: "Chip is a unique NFT that represents a node in the network. It is generated based on the node's address and token ID."
          image: "https://gi.rss3.dev/chips/474/image.svg"
        value: "5000000000000000000000"
        latestValue: "5500000000000000000000"
    Node:
      type: object
      properties:
        id:
          type: integer
        address:
          type: string
        name:
          type: string
        description:
          type: string
        taxRateBasisPoints:
          type: integer
          nullable: true
        isPublicGood:
          type: boolean
        operationPoolTokens:
          type: string
        stakingPoolTokens:
          type: string
        totalShares:
          type: string
        slashedTokens:
          type: string
        status:
          type: string
          enum:
            - registered
            - online
            - offline
            - exited
        lastHeartbeat:
          type: integer
          description: "The timestamp of the last heartbeat"
        local:
          type: array
          items:
            type: object
            properties:
              country:
                type: string
              region:
                type: string
              city:
                type: string
              latitude:
                type: number
              longitude:
                type: number
        avatar:
          type: object
          properties:
            name:
              type: string
            image:
              type: string
            description:
              type: string
        minTokensToStake:
          type: string
        createAt:
          type: integer
          description: "The timestamp of the node creation"
      example:
        id: 1
        address: "0xc5999271b01afc77ed7a6738b40c34677c2a581c"
        name: "RSS3 Node"
        description: "Get started with RSS3 Node with symphonia"
        taxRateBasisPoints: 1000
        isPublicGood: false
        operationPoolTokens: "10000000000000000000000"
        stakingPoolTokens: "0"
        totalShares: "0"
        slashedTokens: "0"
        status: "online"
        lastHeartbeat: 1709117916
        local:
          - country: "CN"
            region: "GD"
            city: "SZ"
            latitude: 22.5431
            longitude: 114.0579
        avatar:
          - name: "Node Avatar"
            description: ""
            image: "http://127.0.0.1/nodes/0xC5999271b01AfC77ED7a6738b40C34677C2A581c/avatar.svg"
        minTokensToStake: "0"
        createdAt: 1709087910
    NodeEvent:
      type: object
      properties:
        addressFrom:
          type: string
        addressTo:
          type: string
        nodeID:
          type: integer
        type:
          type: string
          enum:
              - nodeCreated
        logIndex:
          type: integer
        chainID:
          type: integer
        block:
          type: object
          properties:
            hash:
              type: string
            number:
              type: integer
            timestamp:
              type: integer
        transaction:
          type: object
          properties:
            hash:
              type: string
            index:
              type: integer
        metadata:
          type: object
          properties:
            nodeCreated:
              type: object
              properties:
                nodeID:
                  type: integer
                address:
                  type: string
                name:
                  type: string
                description:
                  type: string
                taxRateBasisPoints:
                  type: integer
                isPublicGood:
                  type: boolean
    NodeMinTokensToStakeSnapshot:
      type: object
      properties:
        nodeAddress:
          type: string
        snapshots:
          type: array
          items:
            type: object
            properties:
              date:
                type: string
                example: "2024-03-13T00:08:38+08:00"
              epochID:
                type: integer
              nodeAddress:
                type: string
              minTokensToStake:
                type: string
              createdAt:
                type: string
              updatedAt:
                type: string
    StakerProfitSnapshot:
      type: object
      properties:
        ownerAddress:
          type: string
        date:
          type: string
          example: "2024-03-13T00:08:38+08:00"
        epochID:
          type: integer
        totalChipAmounts:
          type: string
        totalChipValues:
          type: string
    ChipPNL:
      type: object
      properties:
        date:
          type: string
        totalChipAmounts:
          type: string
        totalChipValues:
          type: string
        pnl:
          type: string
    OperatorProfitSnapshot:
      type: object
      properties:
        operator:
          type: string
        date:
          type: string
          example: "2024-03-13T00:08:38+08:00"
        epochID:
          type: integer
        operationPool:
          type: string
